### ISSUE TITLE
Docker + Traefik confusion + Nginx issues

### ISSUE THREAD

**Issue by angelfor3v3r** [jkcclemens/paste#234]
Hi!

I'm trying to get this running on my domain and have a few issues and questions.

All of these are when running with the provided compose command:

1. Nginx fails to run because of this, so no web server.
```
nginx_1     | 2020/03/02 06:41:12 [emerg] 1#1: dlopen() "/etc/nginx/extra_modules/ngx_http_brotli_static_module.so" failed (Error loading shared library /etc/nginx/extra_modules/ngx_http_brotli_static_module.so: Exec format error) in /etc/nginx/nginx.conf:4
nginx_1     | nginx: [emerg] dlopen() "/etc/nginx/extra_modules/ngx_http_brotli_static_module.so" failed (Error loading shared library /etc/nginx/extra_modules/ngx_http_brotli_static_module.so: Exec format error) in /etc/nginx/nginx.conf:4
```

2. Postgres fails to connect to the DB.
```
postgres_1  | 2020-03-02 06:42:27.501 UTC [48] FATAL:  password authentication failed for user "root"
postgres_1  | 2020-03-02 06:42:27.501 UTC [48] DETAIL:  Role "root" does not exist.
postgres_1  |   Connection matched pg_hba.conf line 95: "host all all all md5"
```
Is there a config I'm missing for this? According to the compose file it should be using `paste:paste` as the login.

3. This is a confusing one. Why must we have cert files when running behind Traefik, etc. Shouldn't the reverse proxy be in charge of this? Regardless, this is an error for me, even after copying the certs from Traefik.
```
backend_1   | Error: I/O error while setting tls.certs:
backend_1   |     => No such file or directory (os error 2)
```

4. A final question: How would you even get this to run through traefik anyway? Exposing ports 80 and 443 is wrong since those are already open externally (by traefik). Is it safe to remove the port exposing in the compose file and pass the `https://0.0.0.0:8000` or `80/443` from nginx to Traefik?

snip from the compose file you provided:
```
nginx:
    build: nginx
    restart: unless-stopped
    depends_on:
      - backend
      - camo
    # ports: # don't expose these when using Traefik. Route traffic internally
    #   - "1337:1337"
    #   - "1338:1338"
    
    labels:
        # enable this service so traefik can see it
        - "traefik.enable=true"

        # route eccologic.net frontpage
        - "traefik.http.routers.dynmap.rule=Host( `dynmap.eccologic.net` )"
        - "traefik.http.routers.dynmap.tls=true"
        - "traefik.http.routers.dynmap.tls.options=custom@file"
        - "traefik.http.routers.dynmap.entrypoints=web-secure"
        - "traefik.http.services.dynmap.loadbalancer.server.port=443" # uhh? maybe this should be under `backend`.
    
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./nginx/sites:/etc/nginx/sites:ro"
      - "./nginx/certs:/etc/nginx/certs:ro"
      - "./nginx/extra_modules:/etc/nginx/extra_modules:ro"
      - "../webserver/web/static:/etc/nginx/web/static:ro"
```

**Comment by jkcclemens** [comment]
> Nginx fails to run because of this, so no web server.

You need to clone with git lfs to get the modules, but you shouldn't be using the `nginx` container from what I've read.

> Postgres fails to connect to the DB.

No, it doesn't. Postgres can't fail to connect to itself. Those log lines are from the backend script checking to see if postgres is up before starting the backend. You can ignore them.

> Why must we have cert files when running behind Traefik, etc. Shouldn't the reverse proxy be in charge of this?

There was a reason, though I can't remember why any more. I would look into it, but paste is very low on my list of priorities recently, and this aspect of it is lowest. If you care enough, you can look and see about not requiring TLS.

> Regardless, this is an error for me, even after copying the certs from Traefik.

The certs have to be included in the nginx docker container via a volume. Then you just tell the config file where to find them in the container. For example, paste.gg has this in Rocket.toml:

```toml
# uncomment this to enable server TLS
[global.tls]
certs = "/paste/certs/fullchain.pem"
key = "/paste/certs/privkey.pem"
```

The `docker-compose.yml` has a volume of `/path/to/certs/on/host:/paste/certs:ro`.

> A final question: How would you even get this to run through traefik anyway? Exposing ports 80 and 443 is wrong since those are already open externally (by traefik). Is it safe to remove the port exposing in the compose file and pass the https://0.0.0.0:8000 or 80/443 from nginx to Traefik?

I don't know anything about Traefik or even what it is. Assuming you're trying to use it as a reverse proxy, just expose port 8000 from the `backend` container on localhost and make Traefik use it. You can comment out the `nginx` container if you're not going to be using nginx (or if you want to use nginx already on the host, etc.).

```yaml
services:
  backend:
    # ...
    ports:
      - "127.0.0.1:8000:8000"
```
