### ISSUE TITLE
Can't copy paste footer

### ISSUE THREAD

**Issue by lol768** [jkcclemens/paste#42]
For some dumb reason, (presumably) Bulma breaks user expectations by stopping text selection:

```css
.breacrumb {
    -webkit-touch-callout: none;
    -webkit-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
}
```
